college_app/urls.py
from django.conf.urls import url
from college_app import views

app_name = 'college_app'

urlpatterns = [
  url(r'^$',views.SchoolListView.as_view(),name='list'),
  url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
  url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
  url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),


]

college_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from college_app import views

urlpatterns = [
    url(r'^college_app/',include('college_app.urls',namespace='college_app')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view())
]

college_app/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=10)
    principal = models.CharField(max_length=10)
    location = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("college_app:detail", kwargs={'pk': self.pk})



class Student(models.Model):
    name = models.CharField(max_length=10)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students')

    def __str__(self):
        return self.name

college_app/views.py
from django.http import HttpResponse
from django.views.generic import View, TemplateView, DetailView, ListView, CreateView, UpdateView, DeleteView
from college_app import models
from django.core.urlresolvers import reverse_lazy

# from college_app import models

# Create your views here.

# class IndexView(View):
#     def get(self, request):
#         return HttpResponse('hello world')

class IndexView(TemplateView):
    template_name = 'college_app/index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'college_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ("name", "principal")
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("college_app:list")

college_app/templates/college_app/school_confirm_delete.html
{% extends 'college_app/base_app.html' %}
{% block body_block %}
  <h1>Delete {{ school.name }}</h1>

  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <a href="{% url 'college_app:detail' pk=school.pk %}">Cancel</a>
  </form>
{% endblock %}

college_app/templates/college_app/school_detail.html
{% extends 'college_app/base_app.html'%}

{% block body_block %}
  <h1>Welcome to College Detail Page</h1>
  <h2>College details: </h2>
  <p>Name: {{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principal }}</p>
  <p>Location: {{ school_detail.location }}</p>
  <h3>Students:</h3>

  {% for student in school_detail.students.all %}
    {% if student  %}
      <p>{{ student.name }} who is {{ student.age }} years old</p>
    {% else %}
     <p>No students enrolled in this college<p>
    {% endif %}
  {% endfor %}

    <div >

      <button><a href="{% url 'college_app:update' pk=school_detail.pk %}">Update</a></button>

  </div>
{% endblock %}

college_app/templates/college_app/school_form.html
{% extends 'college_app/base_app.html' %}

{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create School
    {% else %}
      Update School
    {% endif %}
  </h1>

  <form  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

college_app/templates/college_app/school_list.html
{% extends 'college_app/base_app.html' %}

{% block body_block %}
  <h1>Welcome to the list of Colleges: </h1>
  <ul>
    {% for school in schools %}
      <h2><li><a href="{{school.id}}/">{{school.name}} </a></li></h2>
    {% endfor %}
  </ul>
{% endblock %}

templates/college_app/base_app.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Testing CLass Based Views on BASED PAGE</title>
  </head>
  <body>
    <h1>NAVBAR</h1>
    <nav>
        <ul>
          <li><a href="{% url 'college_app:list' %}">Schools</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
          <li><a href="#"></a></li>
        </ul>
    </nav>
    <div>
      {% block body_block %}

      {% endblock %}
  </divs>
  </body>
</html>

templates/college_app/index.html
{% extends 'college_app/base_app.html' %}

{% block body_block %}
  <h1> index page: I figured it out </h1>
{% endblock %}